home: "{{ ansible_env.HOME }}"

my_dir: "{{ home }}/.my"
my_dir_bin: "{{ my_dir }}/bin"
my_dir_notes: "{{ my_dir }}/notes"
my_dir_dotfiles: "{{ my_dir }}/dotfiles"

dir_config: "{{ home }}/.config"
dir_dev: "{{ home }}/dev"

git_name: "waiq"
