---
- name: Remove old golang installation
  ansible.builtin.file:
    path: "{{ core.dirs.local}}/go"
    state: absent

- name: Download new golang version
  ansible.builtin.get_url:
    url: https://go.dev/dl/go1.21.5.linux-amd64.tar.gz
    dest: "{{ core.dirs.local }}/go1.21.5.linux-amd64.tar.gz"
    checksum: sha256:e2bc0b3e4b64111ec117295c088bde5f00eeed1567999ff77bc859d7df70078e

- name: Install golang
  ansible.builtin.unarchive:
    src: "{{ core.dirs.local }}/go1.21.5.linux-amd64.tar.gz"
    dest: "{{ core.dirs.local }}"

- name: Setup init for golang
  ansible.builtin.template:
    src: "{{ core.dirs.custom }}/roles/golang/templates/init_d/10-golang.j2"
    dest: "{{ core.dirs.init_d }}/10-golang.sh"
