---
- name: Install tmux
  ansible.builtin.apt:
    name: tmux
    state: present
  become: yes
  become_user: root
  become_method: sudo

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ home }}/.tmux/plugins/tpm"
    update: yes
  become: yes
  become_user: root
  become_method: sudo

- name: Link tmux config
  ansible.builtin.file:
    src: "{{ core.dirs.custom }}/roles/tmux/files/tmux.conf"
    dest: "{{ home }}/.tmux.conf"
    state: link
