---
- name: Install flatpak
  ansible.builtin.apt:
    name: flatpak
    state: present
  become: true
  become_user: root
  become_method: ansible.builtin.sudo

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
