---
- name: Install git
  ansible.builtin.apt:
    pkg:
      - git
      - tig
    state: present
  become: true
  become_user: root
  become_method: ansible.builtin.sudo

- name: Check if gitconfig exists
  ansible.builtin.stat:
    path: "{{ home }}/.gitconfig"
  register: gitconfig

- name: Back up gitconfig
  ansible.builtin.copy:
    src: "{{ home }}/.gitconfig"
    dest: "{{ home }}/.gitconfig.bak"
    mode: "0644"
  when: gitconfig.stat.exists

- name: Remove old gitconfig
  ansible.builtin.file:
    path: "{{ home }}/.gitconfig"
    state: absent
  when: gitconfig.stat.exists

- name: Make sure gitconfig is up to date
  ansible.builtin.template:
    src: "{{core.dirs.custom}}/roles/git/templates/gitconfig.j2"
    dest: "{{ home }}/.gitconfig"
    mode: "0644"

- name: Make sure gitignore is up to date
  ansible.builtin.template:
    src: "{{core.dirs.custom}}/roles/git/templates/gitignore.j2"
    dest: "{{ home }}/.gitignore"
    mode: "0644"

- name: "setup init"
  ansible.builtin.template:
    src: "{{ core.dirs.custom }}/roles/git/templates/init_d/10-git.j2"
    dest: "{{ core.dirs.init_d }}/10-git.sh"
    mode: "0755"
