---
- name: Upgrade apt
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  become: true
  become_method: ansible.builtin.sudo

- name: Install apt packages
  ansible.builtin.apt:
    pkg:
      - cheese
      - gnupg
      - software-properties-common
      - aptitude
      - tidy
      - libgtk-4-dev
      - build-essential
      - stow
      - make
      - curl
      - wget
      - htop
      - jq
      - ripgrep
      - libfuse2
      - python3-venv
      - composer
      - fzf
      - network-manager-l2tp
      - network-manager-l2tp-gnome
      - fd-find
  become: true
  become_method: ansible.builtin.sudo

- name: Remove apt packages
  ansible.builtin.apt:
    pkg:
      - gnome-shell-extension-ubuntu-dock
    state: absent
  become: true
  become_method: ansible.builtin.sudo

  # Clipboard setup
- name: "Clipboard x11"
  when: (lookup('ansible.builtin.env', 'XDG_SESSION_TYPE')) == 'x11'
  block:
    - name: Install xset clipboard
      ansible.builtin.apt:
        name: "xsel"
        update_cache: true
      become: true
      become_method: ansible.builtin.sudo

    - name: Remove wl-clipboard
      ansible.builtin.apt:
        name: "wl-clipboard"
        update_cache: true
        state: absent
      become: true
      become_method: ansible.builtin.sudo

- name: "Clipboard Wayland"
  when: (lookup('ansible.builtin.env', 'XDG_SESSION_TYPE')) == 'wayland'
  block:
    - name: Install wl-clipboard clipboard
      ansible.builtin.apt:
        name: "wl-clipboard"
        update_cache: true
      become: true
      become_method: ansible.builtin.sudo

    - name: Remove xset clipboard
      ansible.builtin.apt:
        name: "xsel"
        update_cache: true
        state: absent
      become: true
      become_method: ansible.builtin.sudo
