---
- name: Install Dropbox
  ansible.builtin.apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
  become: true
  become_method: ansible.builtin.sudo
  when: ansible_facts['lsb']['release'] == "22.04"

- name: Install libgtk-4-dev
  ansible.builtin.apt:
    name: libgtk-4-dev
    state: present
  become: true
  become_method: ansible.builtin.sudo
  when: ansible_facts['lsb']['release'] != "22.04"

- name: Install Dropbox
  ansible.builtin.apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2023.09.06_amd64.deb
  become: true
  become_method: ansible.builtin.sudo
  when: ansible_facts['lsb']['release'] != "22.04"

- name: "Dropbox setup init"
  ansible.builtin.template:
    src: "{{ core.dirs.custom }}/roles/dropbox/templates/init_d/10-dropbox.j2"
    dest: "{{ core.dirs.init_d }}/10-dropbox.sh"
    mode: "0755"
