---

- name: Install Dropbox
  ansible.builtin.apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_facts['lsb']['release'] == "22.04"

- name: Install libgtk-4-dev
  ansible.builtin.apt:
    name: libgtk-4-dev
    state: present
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_facts['lsb']['release'] != "22.04"

- name: Install Dropbox
  ansible.builtin.apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2023.09.06_amd64.deb
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_facts['lsb']['release'] != "22.04"


