---
- name: "Install aws"
  ansible.builtin.debug:
    msg: "aws"

- name: "Create temporary download directory"
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: temp_dir

- name: "merp"
  ansible.builtin.debug:
    msg: "{{ temp_dir.path }}"

- name: "Download"
  ansible.builtin.unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "{{ temp_dir.path }}/"
    remote_src: true

- name: "Install"
  ansible.builtin.raw: "{{ temp_dir.path }}/aws/install --bin-dir {{ core.dirs.bin }} --install-dir {{ core.dirs.local }}"
