return {
	ensure_installed = {
		"lua-language-server",
		"stylua",
		"codespell",
		"bash-language-server",
		"bash-debug-adapter",
		"html-lsp",
		"css-lsp",
		"gopls",
		"golines",
		"goimports",
		"prettier",
		"sqlls",
		"phpactor",
		"phpstan",
		"php-debug-adapter",
		"remark-language-server",
		"typescript-language-server",
		"dockerfile-language-server",
		"google-java-format",
		"java-debug-adapter",
		"java-test",
		"jdtls",
	},
}
