---
- name: "Install wezterm"
  ansible.builtin.debug:
    msg: "wezterm"

- name: "Add APT Key"
  ansible.builtin.apt_key:
    url: https://apt.fury.io/wez/gpg.key
    keyring: /usr/share/keyrings/wezterm-fury.gpg
    state: present
  become: true

- name: "Add APT Repo"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *"
    state: present
    mode: "0644"
  become: true

- name: "Install wezterm"
  ansible.builtin.apt:
    name: wezterm
    state: present
    update_cache: true
  become: true

- name: Link config
  ansible.builtin.file:
    src: "{{ core.dirs.custom }}/roles/wezterm/files/wezterm.lua"
    dest: "{{ home }}/.wezterm.lua"
    state: link
