---

- name: Install neovim
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
    dest: "{{ core.dirs.bin }}/nvim"
    mode: '0755'

- name: Install NVChad
  ansible.builtin.git:
    repo: 'https://github.com/NvChad/NvChad'
    dest: "{{ user.dirs.config }}/nvim"
    depth: 1
    update: no

- name: Link custom folder
  ansible.builtin.file:
    src: "{{ core.dirs.dotfiles }}/roles/neovim/files/custom"
    dest: "{{ user.config }}/nvim/lua/custom"
    state: link

- name: Link neovim env.d files
  ansible.builtin.file:
    src: "{{ core.dirs.dotfiles }}/roles/nvim/files/env.d/{{ item }}"
    dest: "{{ core.dirs.env_d }}/{{ item }}"
    state: link
  loop:
    - "10-nvim.sh"


