---
- name: Create folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ my }}"
    - "{{ core.dirs.bin }}"
    - "{{ core.dirs.local }}"
    - "{{ core.dirs.dotfiles }}"
    - "{{ core.dirs.init }}"
    - "{{ core.dirs.init_d }}"
    - "{{ core.dirs.custom_d }}"
    - "{{ core.dirs.cache }}"

- name: Checkout dotfiles
  ansible.builtin.git:
    repo: "{{ core.git.repository }}"
    dest: "{{ core.dirs.dotfiles }}"
    update: true
    version: "{{ core.git.version }}"
  when: install.git_pull

- name: Set dotfiles github name
  community.general.git_config:
    name: user.name
    repo: "{{ core.dirs.dotfiles }}"
    scope: local
    value: "{{ core.git.name }}"

- name: Set dotfiles github email
  community.general.git_config:
    name: user.email
    repo: "{{ core.dirs.dotfiles }}"
    scope: local
    value: "<>"

- name: Setup init.sh
  ansible.builtin.template:
    src: "{{ core.dirs.dotfiles }}/core/roles/setup/templates/init/init.j2"
    dest: "{{ core.dirs.init }}/init.sh"
    mode: "0755"

- name: Setup init folder
  ansible.builtin.template:
    src: "{{ core.dirs.dotfiles }}/core/roles/setup/templates/init/1-dotfiles-env.j2"
    dest: "{{ core.dirs.init_d }}/1-dotfiles-env.sh"
    mode: "0755"

- name: Setup dotrun completions
  ansible.builtin.template:
    src: "{{ core.dirs.dotfiles }}/core/roles/setup/templates/init/1-dotfiles-dotrun-completions.j2"
    dest: "{{ core.dirs.init_d }}/1-dotfiles-dotrun-completions.sh"
    mode: "0755"

- name: Setup bin file dotrun
  ansible.builtin.template:
    src: "{{ core.dirs.dotfiles }}/core/roles/setup/templates/bin/dotrun.j2"
    dest: "{{ core.dirs.bin }}/dotrun"
    mode: "0755"
