---
- name: Install neovim
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
    dest: "{{ core.dirs.bin }}/nvim"
    mode: "0755"

- name: Link custom folder
  ansible.builtin.file:
    src: "{{ core.dirs.custom }}/roles/nvim/files"
    dest: "{{ custom.dirs.config }}/nvim"
    state: link

- name: Create neovim init_d files
  ansible.builtin.template:
    src: "{{ core.dirs.custom }}/roles/nvim/templates/init_d/10-nvim.j2"
    dest: "{{ core.dirs.init_d }}/10-nvim.sh"
    mode: "0755"

- name: Create neovim custom_d files
  ansible.builtin.template:
    src: "{{ core.dirs.custom }}/roles/nvim/templates/custom_d/10-nvim.j2"
    dest: "{{ core.dirs.custom_d }}/10-nvim.sh"
    mode: "0755"
