---
- name: "Install nvm"
  ansible.builtin.debug:
    msg: "nvm"

- name: "Check for nvm installation"
  ansible.builtin.stat:
    path: "{{ home }}/.nvm"
  register: nvm

- name: "Install nvm"
  when: not nvm.stat.exists
  block:
    - name: "Get latest version"
      ansible.builtin.uri:
        url: https://api.github.com/repos/nvm-sh/nvm/releases/latest
        return_content: true
      register: json_reponse

    - name: "Installing version"
      ansible.builtin.debug:
        msg: "{{ json_reponse.json.tag_name }}"

    - name: "Install nvm"
      ansible.builtin.shell: >
        PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/"{{ json_reponse.json.tag_name }}"/install.sh | bash'
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: "Setup init for nvm"
  ansible.builtin.template:
    src: "{{ core.dirs.custom }}/roles/nvm/templates/init_d/10-nvm.j2"
    dest: "{{ core.dirs.init_d }}/10-nvm.sh"
    mode: "0644"

# indtall node versions
- name: "Install Node.js"
  ansible.builtin.shell: >
    "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{item}}"
  with_items:
    - "--lts"
