---
- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "Install"
  when: "'slack-desktop' not in ansible_facts.packages"
  block:
    - name: "Download"
      ansible.builtin.get_url:
        url: https://slack.com/downloads/instructions/linux?ddl=1&build=deb
        dest: /tmp/slack-desktop.deb
        mode: "0755"
        force: "yes"

    - name: "Install"
      ansible.builtin.apt:
        deb: /tmp/slack-desktop.deb
      become: true
      become_method: ansible.builtin.sudo
