---
- name: "Add APT Key"
  ansible.builtin.apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    keyring: /usr/share/keyrings/1password-archive-keyring.gpg
    state: present
  become: true

- name: "Add APT Repo"
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_machine | replace('x86_64', 'amd64') }} signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/{{ ansible_machine | replace('x86_64', 'amd64') }} stable main"
    state: present
    mode: "0644"
  become: true

- name: "Add debsig-verify policy"
  become: true
  block:
    - name: "Ensure policy directory exists"
      ansible.builtin.file:
        name: /etc/debsig/policies/AC2D62742012EA22
        state: directory
        mode: "0755"

    - name: "Copy debsig-verify policy"
      ansible.builtin.get_url:
        url: https://downloads.1password.com/linux/debian/debsig/1password.pol
        dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
        mode: "0644"

    - name: "Ensure debsig keyring directory exists"
      ansible.builtin.file:
        name: /usr/share/debsig/keyrings/AC2D62742012EA22
        state: directory
        mode: "0755"

    - name: "Add debsig keyring"
      ansible.builtin.apt_key:
        url: https://downloads.1password.com/linux/keys/1password.asc
        keyring: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

- name: "Install 1Password-cli"
  ansible.builtin.apt:
    name: 1password-cli
    state: present
    update_cache: true
  become: true

- name: "Install 1Password"
  ansible.builtin.apt:
    name: 1password
    state: present
    update_cache: true
  become: true

- name: "Create 1password init_d files"
  ansible.builtin.template:
    src: "{{ core.dirs.custom }}/roles/1password/templates/init_d/10-1password.j2"
    dest: "{{ core.dirs.init_d }}/10-1password.sh"

- name: Ensure Git remote is using SSH
  git:
    repo: "{{ git_repo_path }}"
    remote: "{{ git_remote_name }}"
    version: master
    # This is the SSH URL you want to set
    ssh_opts: "-o StrictHostKeyChecking=no"
    clone: no
    track_submodules: no
  register: git_info

- name: Get the current remote URL
  command: git remote get-url {{ git_remote_name }}
  args:
    chdir: "{{ git_repo_path }}"
  register: current_remote_url

- name: Change remote URL from HTTPS to SSH
  command: git remote set-url {{ git_remote_name }} {{ ssh_remote_url }}
  args:
    chdir: "{{ git_repo_path }}"
  when: "'https' in current_remote_url.stdout and ssh_remote_url not in current_remote_url.stdout"
  register: remote_change

- name: Confirm the remote URL has been changed
  command: git remote get-url {{ git_remote_name }}
  args:
    chdir: "{{ git_repo_path }}"
  when: remote_change is changed
  register: new_remote_url

- debug:
    msg: "Remote URL changed to {{ new_remote_url.stdout }}"
  when: remote_change is changed
