---
- name: "Install"
  ansible.builtin.set_fact:
    package_name: "mongodb-mongosh"
    package_repo: "https://api.github.com/repos/mongodb-js/mongosh/releases/latest"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "Check whether a package is installed"
  ansible.builtin.set_fact:
    install_check: "{{ ansible_facts.packages[package_name] | default([]) }}"

- name: "Install"
  when: install_check | length == 0
  block:
    - name: Check latest version
      ansible.builtin.uri:
        url: "{{ package_repo }}"
        return_content: true
      register: release

    - name: "Extract .deb asset URL"
      ansible.builtin.set_fact:
        asset_url: "{{ release.json.assets | selectattr('name', 'search', '^mongodb-mongosh_.*_amd64.deb$') | map(attribute='browser_download_url') | first }}"

    - name: Check latest version
      ansible.builtin.debug:
        var: "{{ asset_url }}"

    - name: "Installing {{ release.json.tag_name }}"
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.apt:
        deb: "{{ asset_url }}"

- name: "Create init_d files"
  ansible.builtin.template:
    src: "{{ core.dirs.custom }}/roles/mongodb-mongosh/templates/init_d/10-mongodb-mongosh.j2"
    dest: "{{ core.dirs.init_d }}/10-mongodb-mongosh.sh"
    mode: "0755"
