#!/bin/bash
# Usage: tmux-send-notification <session> [pane] <message>

SESSION="$1"
shift

if [[ "$1" =~ ^[0-9]+$ ]]; then
  PANE="$1"
  shift
else
  PANE=""
fi

MESSAGE="$*"
LOGFILE="$HOME/.tmux/notifications.log"

if [[ -z "$SESSION" || -z "$MESSAGE" ]]; then
  echo "Usage: tmux-send-notification <session> [pane] <message>"
  exit 1
fi

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
echo "$TIMESTAMP|$SESSION|$PANE|$MESSAGE" >> "$LOGFILE"

tmux display-message -t "$SESSION" "Notification: $MESSAGE"

echo "Sent to $SESSION: $MESSAGE"
