---
- name: "Install terraform"
  ansible.builtin.debug:
    msg: "terraform"

- name: Add HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: "0644"
  become: true
  become_method: ansible.builtin.sudo

- name: Add Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_machine | replace('x86_64', 'amd64') }} signed-by=/usr/share/keyrings/terraform.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    mode: "0644"
    filename: "hashicorp"
  become: true
  become_method: ansible.builtin.sudo

- name: Install
  ansible.builtin.apt:
    pkg:
      - terraform
    state: present
    update_cache: true
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
