---
- name: "Check fonts directory"
  ansible.builtin.stat:
    path: "{{ home }}/.fonts"
  register: p

- name: "Install fonts"
  block:
    - name: "Create fonts directory"
      ansible.builtin.file:
        path: "{{ home }}/.fonts"
        state: directory
        mode: "0755"

    - name: "Download fonts"
      ansible.builtin.unarchive:
        src: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip"
        dest: "{{ home }}/.fonts/"
        remote_src: true

    - name: "Download fonts symbols"
      ansible.builtin.unarchive:
        src: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/NerdFontsSymbolsOnly.zip"
        dest: "{{ home }}/.fonts/"
        remote_src: true

  when: not p.stat.exists
