---
- ansible.builtin.set_fact:
    package_name: "glab"
    package_repo: "https://gitlab.com/api/v4/projects/gitlab-org%2Fcli/releases"

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: "Check whether a package is installed"
  ansible.builtin.set_fact:
    install_check: "{{ ansible_facts.packages[package_name] | default([]) }}"

- name: "Install"
  when: install_check | length == 0
  block:
    - name: Check latest version
      ansible.builtin.uri:
        url: "{{ package_repo }}"
        return_content: true
      register: release

    - name: Extract .deb asset URL
      set_fact:
        asset_name: "{{ release.json[0].assets.links | selectattr('name', 'search', 'Linux_x86_64.deb$') | map(attribute='name') | first }}"
        asset_url: "{{ release.json[0].assets.links | selectattr('name', 'search', 'Linux_x86_64.deb$') | map(attribute='url') | first }}"

    - name: Check latest version
      ansible.builtin.debug:
        msg: "{{ asset_url }}"

    - name: "Installing {{ asset_name }}"
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.apt:
        deb: "{{ asset_url }}"
