---
- name: Set up local workstation
  hosts: local
  vars_files:
    ./common/vars.yml
  roles:
    - role: apt
      tags:
        apt
    - role: fonts
      tags:
        fonts
    - role: neovim
      tags: 
        neovim
    - role: tmux
      tags: 
        tmux
    - role: git
      tags: 
        git
    - role: zsh
      tags:
        zsh
