- name: Create folders
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{ my_dir }}"
    - "{{ my_dir_bin }}"
    - "{{ my_dir_notes }}"
    - "{{ my_dir_dotfiles }}"
    - "{{ my_dir_env }}"
    - "{{ my_dir_env_d }}"
    - "{{ dir_dev }}"

- name: Checkout dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:waiq/dotfiles.git'
    dest: "{{ my_dir_dotfiles }}"
    update: yes
    version: "wip-ansible"
    
- name: Set dotfiles github name
  community.general.git_config:
    name: user.name
    repo: "{{ my_dir_dotfiles }}"
    scope: local
    value: 'waiq'

- name: Set dotfiles github email
  community.general.git_config:
    name: user.email
    repo: "{{ my_dir_dotfiles }}"
    scope: local
    value: '<>'

- name: Link load_env.sh
  ansible.builtin.file:
    src: "{{ my_dir_dotfiles }}/roles/setup/files/env/load_env.sh"
    dest: "{{ my_dir_env }}/load_env.sh"
    state: link
