---
- name: "Check if installed"
  ansible.builtin.set_fact:
    package_name: "zoom"
    package_repo: "https://zoom.us/client/6.1.11.1545/zoom_amd64.deb"

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: "Check whether a package is installed"
  ansible.builtin.set_fact:
    install_check: "{{ ansible_facts.packages[package_name] | default([]) }}"

- name: "Install"
  when: install_check | length == 0
  block:
    - name: "deb"
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.apt:
        deb: "{{ package_repo }}"
