---
- name: "Install mongodb-sh"
  ansible.builtin.debug:
    msg: "mongodb-sh"

- name: "Check if installed"
  ansible.builtin.shell: command -v mongosh
  register: mongosh_check
  changed_when: false
  ignore_errors: true

- name: "Install"
  when: mongosh_check.rc != 0
  block:
    - name: Check latest version
      ansible.builtin.uri:
        url: https://api.github.com/repos/mongodb-js/mongosh/releases/latest
        return_content: true
      register: latest

    - name: Check latest version
      ansible.builtin.debug:
        var: "https://github.com/mongodb-js/mongosh/releases/download/{{ latest.json.tag_name }}/mongodb-mongosh_{{ latest.json.name }}_amd64.deb"

    - name: "Installing {{ latest.json.tag_name }}"
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.apt:
        deb: "https://github.com/mongodb-js/mongosh/releases/download/{{ latest.json.tag_name }}/mongodb-mongosh_{{ latest.json.name }}_amd64.deb"

- name: "Create init_d files"
  ansible.builtin.template:
    src: "{{ core.dirs.custom }}/roles/mongodb-sh/templates/init_d/10-mongodb-sh.j2"
    dest: "{{ core.dirs.init_d }}/10-mongodb-sh.sh"
