---
- name: "Install spotify"
  ansible.builtin.debug:
    msg: "spotify"

- name: Download Spotify GPG key
  ansible.builtin.get_url:
    url: https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg
    dest: /usr/share/keyrings/spotify.gpg
    mode: "0644"
  become: true
  become_method: ansible.builtin.sudo

- name: Add Spotify repository with signed-by option
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/spotify.gpg] http://repository.spotify.com stable non-free"
    state: present
    update_cache: yes
  become: true
  become_method: ansible.builtin.sudo

- name: Upgrade apt
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  become: true
  become_method: ansible.builtin.sudo

- name: Install Spotify
  ansible.builtin.apt:
    pkg: spotify-client
    state: present
    update_cache: true
  become: true
  become_method: ansible.builtin.sudo
