---
- name: "Install apt packages"
  ansible.builtin.apt:
    name: "gnome-tweaks"
    update_cache: true
  become: true
  become_method: ansible.builtin.sudo

- name: Check if catppuccin terminal theme exists
  ansible.builtin.stat:
    path: "{{ core.dirs.cache }}/gnome-terminal-catppuccin-theme"
  register: p

- name: "Install terminal theme"
  when: not p.stat.exists
  block:
    # Gnome terminal theme
    - name: Install catppuccin theme for gnome terminal
      ansible.builtin.raw: "curl -L https://raw.githubusercontent.com/catppuccin/gnome-terminal/v0.2.0/install.py | python3 -"
      changed_when: true
      when: not p.stat.exists

    - name: Add cache file
      ansible.builtin.file:
        path: "{{ core.dirs.cache }}/gnome-terminal-catppuccin-theme"
        state: "touch"
        mode: "0644"

- name: Get tilingshell facts
  ansible.builtin.stat:
    path: "~/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com"
  register: extension_tilingshell

- name: Ensure the destination directory exists
  when: not extension_tilingshell.stat.exists
  ansible.builtin.file:
    path: "~/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com"
    state: directory

- name: "Download tailing extension"
  when: not extension_tilingshell.stat.exists
  ansible.builtin.unarchive:
    src: "https://github.com/domferr/tilingshell/releases/download/12.2.0/GNOME.42-44.tilingshell@ferrarodomenico.com.zip"
    dest: "~/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com"
    remote_src: true

- name: "Enable tailing extension NEEDS TO RESTART GNOME ALT+F2 and r"
  ansible.builtin.shell: "gnome-extensions enable tilingshell@ferrarodomenico.com"

- name: "Disable workspace animation"
  ansible.builtin.shell: "gsettings set org.gnome.desktop.interface enable-animations false"
