---
- name: Check if catppuccin terminal theme exists
  ansible.builtin.stat:
    path: "{{ core.dirs.cache }}/gnome-terminal-catppuccin-theme"
  register: p

- name: "Install terminal theme"
  when: not p.stat.exists
  block:
    # Gnome terminal theme
    - name: Install catppuccin theme for gnome terminal
      ansible.builtin.raw: "curl -L https://raw.githubusercontent.com/catppuccin/gnome-terminal/v0.2.0/install.py | python3 -"
      changed_when: true
      when: not p.stat.exists

    - name: Add cache file
      ansible.builtin.file:
        path: "{{ core.dirs.cache }}/gnome-terminal-catppuccin-theme"
        state: "touch"
        mode: "0644"

- name: "Install apt packages"
  ansible.builtin.apt:
    name: "gnome-tweaks"
    update_cache: true
  become: true
  become_method: ansible.builtin.sudo
