---
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  become_method: ansible.builtin.sudo

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: true
  become_method: ansible.builtin.sudo

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - gnupg
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true
  become_method: ansible.builtin.sudo

- name: Set user to docker group
  become: yes
  become_method: ansible.builtin.sudo
  ansible.builtin.shell: "usermod -aG docker $USER"
  args:
    executable: /bin/bash

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: true
