- name: Download neovim
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
    dest: "{{ my_dir_bin }}/nvim"
    mode: '0755'

- name: Install NVChad
  ansible.builtin.git:
    repo: 'https://github.com/NvChad/NvChad'
    dest: "{{ dir_config }}/nvim"
    depth: 1
    update: no

- name: Link custom folder
  ansible.builtin.file:
    src: "{{ my_dir_dotfiles }}/roles/neovim/files/custom"
    dest: "{{ dir_config }}/nvim/lua/custom"
    state: link
