---
- name: "Check if installed"
  ansible.builtin.shell: command -v mongodb-compass
  register: install_check
  changed_when: false
  ignore_errors: true

- name: "Install"
  when: install_check.rc != 0
  block:
    - name: Check latest version
      ansible.builtin.uri:
        url: https://api.github.com/repos/mongodb-js/compass/releases/latest
        return_content: true
      register: latest

    - name: Check latest version
      ansible.builtin.debug:
        var: "https://github.com/mongodb-js/compass/releases/download/{{ latest.json.tag_name }}/mongodb-compass_{{ latest.json.name }}_amd64.deb"

    - name: "Installing {{ latest.json.tag_name }}"
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.apt:
        deb: "https://github.com/mongodb-js/compass/releases/download/{{ latest.json.tag_name }}/mongodb-compass_{{ latest.json.name }}_amd64.deb"
